name: deploy-app

on:
  workflow_run:
    workflows: ["build-push or CI"]   # must match EXACT name
    types: [completed]

jobs:

  deploy-app:

    env: 
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKER_TAG: ${{ github.event.workflow_run.head_sha }}

    runs-on: self-hosted

    steps:

      - name: checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        run: docker compose up -d --build   